---
- name: ensure Awesome WM dependencies are installed
  apt: >
    name={{ item }}
    state=present
  with_items:
  - awesome
  - awesome-extra
  - unagi
  tags:
  - gui
  - wm

- name: ensure Awesome WM configuration repo configured
  git: >
    repo='https://github.com/moon-musick/awesome.git'
    dest=/home/{{ user }}/.config/awesome
    update=no
  sudo_user: "{{ user }}"
  tags:
  - gui
  - wm
