---
- name: cheat | ensure cheat is installed
  pip: >
    name=cheat
    state=present
  tags: ['shelltools']

- name: cheat | ensure cheat config dir is present
  file: >
    path=/home/{{ user }}/.cheat
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=directory
  tags: ['shelltools']

- name: cheat | ensure cheat repository was cloned
  git: >
    repo='git@github.com:moon-musick/.cheat.git'
    dest=/home/{{ user }}/.cheat
    accept_hostkey=True
  tags: ['shelltools']
  sudo_user: "{{ user }}"
