---
# - name: comm apps | ensure Hipchat repo key is configured
#   apt_key: >
#     key='https://www.hipchat.com/keys/hipchat-linux.key'
#     state=present
#   tags: ['commtools', 'gui']
# 
# - name: comm apps | ensure Hipchat repo is configured
#   apt_repository: >
#     repo='deb http://downloads.hipchat.com/linux/apt stable main'
#     state=present
#     update_cache=yes
#   tags: ['commtools', 'gui']

- name: comm apps | ensure comm apps are installed
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - finch
    - mutt
  tags: ['commtools', 'shelltools']

# TODO; finch configuration
# TODO; mutt configuration

# - name: comm apps | ensure Telegram PPA key is configured
#   apt_key: >
#     id=36FD5529
#     keyserver=keyserver.ubuntu.com
#     state=present
#   tags: ['commtools', 'gui']
# 
# - name: comm apps | ensure Telegram PPA is configured
#   apt_repository: >
#     repo='ppa:atareao/telegram'
#     state=present
#     update_cache=yes
#   tags: ['commtools', 'gui']
# 
# - name: comm apps | ensure Telegram is installed
#   apt: >
#     name=telegram
#     state=present
#   tags: ['commtools', 'gui']
# 
# - name: comm apps | ensure Telegram is in PATH
#   file: >
#     src=/opt/telegram/Telegram
#     path=/usr/local/bin/telegram
#     owner=root
#     group=root
#     state=link
#   tags: ['commtools', 'gui']
