---
# - name: ensure Hipchat repo key added
#   apt_key: >
#     key='https://www.hipchat.com/keys/hipchat-linux.key'
#     state=present
# 
# - name: ensure Hipchat repo added
#   apt_repository: >
#     repo='deb http://downloads.hipchat.com/linux/apt stable main'
#     state=present
#     update_cache=yes

- name: ensure comm apps installed
  apt: >
    name={{ item }}
    state=present
  with_items:
    - finch
    - mutt

# - name: ensure Telegram PPA key present
#   apt_key: >
#     id=36FD5529
#     keyserver=keyserver.ubuntu.com
#     state=present
# 
# - name: ensure Telegram PPA present
#   apt_repository: >
#     repo='ppa:atareao/telegram'
#     state=present
#     update_cache=yes
# 
# - name: ensure Telegram installed
#   apt: >
#     name=telegram
#     state=present
# 
# - name: ensure Telegram is in PATH
#   file: >
#     src=/opt/telegram/Telegram
#     path=/usr/local/bin/telegram
#     owner=root
#     group=root
#     state=link
