---
- name: ensure Mendeleydesktop PPA key present
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id=6F036044
    state=present
  tags:
  - gui
  - doctools

- name: ensure Mendeleydesktop PPA present
  apt_repository: >
    repo='deb http://desktop-download.mendeley.com/download/apt stable main'
    state=present
    update_cache=yes
  tags:
  - gui
  - doctools

- name: ensure Zeal PPA key present
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id=2FF96FD1
    state=present
  tags:
  - gui
  - doctools

- name: ensure Zeal PPA present
  apt_repository: >
    repo='ppa:zeal-developers/ppa'
    state=present
    update_cache=yes
  tags:
  - gui
  - doctools

- name: ensure doctools packages installed
  apt: >
    name={{ item }}
    state=present
  with_items:
    - zeal
    - zathura
    - mendeleydesktop
  tags:
  - gui
  - doctools
