---
- name: ensure fzf repository was cloned
  git: >
    repo='https://github.com/junegunn/fzf'
    dest=/home/{{ user }}/.fzf
    depth=1
    update=no
  sudo_user: "{{ user }}"
  tags:
  - shelltools

- name: ensure installation script was run
  shell: /home/{{ user }}/.fzf/install < /dev/null
  args:
    creates: /home/{{ user }}/.fzf/bin/fzf
  sudo_user: "{{ user }}"
  tags:
  - shelltools
