---
- name: dependencies | ensure general dependencies are installed
  apt: >
    name={{ item }}
    state=present
    update_cache=true
    cache_valid_time=3600
  with_items:
  - build-essential
  - autojump
  - cloc
  - dict
  - ncdu
  - tree
  - tofrodos
  - debconf-utils
  - python-pip
  - python-dev
  - python3-pip
  - python3-dev
  - openvpn
  - jq
  - pmount
  - ntp
  - subversion
  tags: ['shelltools', 'dependency']

- name: dependencies | ensure general GUI-dependent packages installed
  apt: >
    name={{ item }}
    state=present
    update_cache=true
    cache_valid_time=3600
  with_items:
  - xclip
  - xautolock
  - gconf2
  - scrot
  - xdotool
  tags: ['gui', 'dependency']

- name: dependencies | ensure zsh installed
  apt: >
    name=zsh
    state=present
    default_release=trusty-backports
  tags: ['shelltools', 'dependency']
