---
- name: dependencies | ensure general dependencies are installed
  apt: >
    name={{ item }}
    state=present
    update_cache=true
    cache_valid_time=3600
  with_items:
  - build-essential
  - autojump
  - cloc
  - dict
  - ncdu
  - tree
  - tofrodos
  - debconf-utils
  - python-pip
  - python-dev
  - python-jedi
  - python3-pip
  - python3-dev
  - python3-jedi
  - openvpn
  - jq
  - pmount
  - ntp
  - subversion
  tags: ['shelltools', 'dependency']

- name: dependencies | ensure general GUI-dependent packages installed
  apt: >
    name={{ item }}
    state=present
    update_cache=true
    cache_valid_time=3600
  with_items:
  - xclip
  - xautolock
  - gconf2
  - scrot
  tags: ['gui', 'dependency']

- name: dependencies | ensure zsh installed
  apt: >
    name=zsh
    state=present
    default_release=trusty-backports
  tags: ['shelltools', 'dependency']

- name: dependencies | ensure python packages installed
  pip: >
    name={{ item }}
    executable=pip2
    state=present
  with_items:
  - csvkit
  - ipython
  - gcalcli
  tags: ['shelltools', 'python']

- name: dependencies | ensure python3 packages installed
  pip: >
    name={{ item }}
    executable=pip3
    state=present
  with_items:
  - ipython
  tags: ['shelltools', 'python']
