---
- name: ensure general dependencies installed
  apt: >
    name={{ item }}
    state=present
    update_cache=true
  with_items:
    - build-essential
    - autojump
    - cloc
    - dict
    - ncdu
    - tree
    - tofrodos
    - debconf-utils
    - python-pip
    - python-dev
    - tmux
    - openvpn
    - jq
  tags:
  - shelltools
  - dependency

- name: ensure general GUI-dependent packages installed
  apt: >
    name={{ item }}
    state=present
    update_cache=true
  with_items:
    - xclip
    - gconf2
  tags:
  - gui
  - dependency

- name: ensure zsh installed
  apt: >
    name=zsh
    state=present
    default_release=trusty-backports
  tags:
  - shelltools
  - dependency

- name: ensure python packages installed
  pip: >
    name={{ item }}
    state=present
  with_items:
    - csvkit
    - ipython
  tags:
  - shelltools
