---
- name: gnome-terminal | ensure gnome-terminal configuration are present
  copy: >
    src=gnome-terminal/gnome-terminal-conf.xml
    dest=/home/{{ user }}/ansible/gnome-terminal-conf.xml
    owner={{ user }}
    group={{ user }}
    mode=0644
  tags: ['gui']

- name: gnome-terminal | ensure gnome-terminal configuration was restored
  shell: gconftool-2 --load gnome-terminal-conf.xml && touch gnome-terminal.lock
  args:
    chdir: /home/{{ user }}/ansible/
    creates: /home/{{ user }}/ansible/gnome-terminal.lock
  sudo_user: "{{ user }}"
  tags: ['gui']
