---
- name: ensure Ansible install dir present
  file: >
    path=/home/{{ user }}/ansible
    owner={{ user }}
    group={{ user }}
    mode=0750
    state=directory

- name: ensure gnome-terminal configuration present
  copy: >
    src=gnome-terminal/gnome-terminal-conf.xml
    dest=/home/{{ user }}/ansible/gnome-terminal-conf.xml
    owner={{ user }}
    group={{ user }}
    mode=0644

# FIXME; permissions bug
# - name: ensure gnome-terminal configuration restored
#   shell: gconftool-2 --load gnome-terminal-conf.xml && touch gnome-terminal.lock
#   args:
#     chdir: /home/{{ user }}
#     creates: /home/{{ user }}/ansible/gnome-terminal.lock
#   sudo_user: "{{ user }}"
