---
- name: ensure Ansible install dir present
  file: >
    path=/home/{{ user }}/ansible
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=directory
  tags:
  - gui

- name: ensure gnome-terminal configuration present
  copy: >
    src=gnome-terminal/gnome-terminal-conf.xml
    dest=/home/{{ user }}/ansible/gnome-terminal-conf.xml
    owner={{ user }}
    group={{ user }}
    mode=0644
  tags:
  - gui

- name: ensure gnome-terminal configuration restored
  shell: gconftool-2 --load gnome-terminal-conf.xml && touch gnome-terminal.lock
  args:
    chdir: /home/{{ user }}/ansible/
    creates: /home/{{ user }}/ansible/gnome-terminal.lock
  sudo_user: "{{ user }}"
  tags:
  - gui
