---
- name: ensure gitwatch dependencies are installed
  apt: >
    name=inotify-tools
    state=present
    update_cache=yes
    cache_valid_time=3600
  tags:
  - shelltools
  - gtd

- name: ensure gitwatch script is available
  template: >
    src=gitwatch/gitwatch.j2
    dest=/usr/local/sbin/gitwatch
    owner=root
    group=root
    mode=0755
  tags:
  - shelltools
  - gtd

- name: ensure supervisord is installed
  pip: >
    name=supervisor
    executable=pip2
    state=present
  tags:
  - shelltools
  - gtd

- name: ensure supervisord config files are available
  template: >
    src=supervisord/{{ item.name }}.j2
    dest={{ item.basepath }}/{{ item.name }}
    owner=root
    group=root
    mode={{ item.mode }}
  with_items:
  - { name: "supervisord",      basepath: "/etc/init.d", mode: "0755" }
  - { name: "supervisord.conf", basepath: "/etc",        mode: "0644" }
  notify:
  - restart supervisord
  tags:
  - shelltools
  - gtd

- name: ensure supervisord is enabled and running
  service: >
    name=supervisord
    enabled=yes
    pattern=/usr/local/bin/supervisord
    state=started
  tags:
  - shelltools
  - gtd
