---
- name: ensure hr installed
  shell: wget https://raw.githubusercontent.com/LuRsT/hr/master/hr -O {{ user }}/bin/hr
  args: 
    creates: "{{ user }}/bin/hr"

- name: ensure hr script has proper permissions
  file: >
    path={{ user }}/bin/hr
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=file
