---
- name: ensure user bin directory present
  file: >
    path=/home/{{ user }}/bin
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=directory

- name: ensure hr installed
  get_url: >
    url='https://raw.githubusercontent.com/LuRsT/hr/master/hr'
    dest=/home/{{ user }}/bin/hr
  # args:
  #   creates: "/home/{{ user }}/bin/hr"

- name: ensure hr script has proper permissions
  file: >
    path=/home/{{ user }}/bin/hr
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=file
