---
- name: ensure i3wm repository is present
  apt_repository: >
    repo='deb http://debian.sur5r.net/i3/ trusty universe'
    state=present
    update_cache=yes
  tags:
  - wm
  - gui
  - i3

# FIXME; fix to use allow-unauthenticated somehow
- name: ensure i3wm keyring is installed
  apt: >
    name=sur5r-keyring
    state=present
    force=yes
  register: i3wm_keyring
  tags:
  - wm
  - gui
  - i3

- name: ensure apt cache is up-do-date if i3wm keyring was modified
  command: apt-get update
  when: i3wm_keyring.changed
  tags:
  - wm
  - gui
  - i3

- name: ensure i3wm packages are installed
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
  - i3
  - i3-wm
  - i3lock
  - i3status
  - lxappearance
  - gtk-chtheme
  - qt4-qtconfig
  tags:
  - wm
  - gui
  - i3

# FIXME; use Dropbox dir directly
- include_vars: dropbox.yml
  tags:
  - wm
  - gui
  - i3

# FIXME; use Dropbox dir directly
# FIXME; get_url downloads HTML/JS
- name: download self-compiled i3 packages if needed
  command: wget -O /home/{{ user }}/ansible/{{ item.deb }} "{{ item.url }}"
  sudo_user: "{{ user }}"
  args:
    creates: /home/{{ user }}/ansible/{{ item.deb }}
  with_items:
  - { deb: "{{ i3gaps_debfile }}",   url: "{{ i3gaps_dropbox_url }}" }
  - { deb: "{{ i3blocks_debfile }}", url: "{{ i3blocks_dropbox_url }}" }
  tags:
  - wm
  - gui
  - i3

# FIXME; use Dropbox dir directly
- name: ensure self-compiled i3 packages are installed
  apt: >
    deb=/home/{{ user }}/ansible/{{ item }}
    state=present
  with_items:
  - "{{ i3gaps_debfile }}"
  - "{{ i3blocks_debfile }}"
  tags:
  - wm
  - gui
  - i3

- name: ensure i3 configuration is synchronized
  git: >
    repo='git@github.com:moon-musick/i3.git'
    dest=/home/{{ user }}/.i3
  sudo_user: "{{ user }}"
  tags:
  - wm
  - gui
  - i3

- name: ensure i3status and i3blocks symlinks exist
  file: >
    src=/home/{{ user }}/.i3/{{ item.src }}
    dest=/home/{{ user }}/{{ item.dest }}
    owner={{ user }}
    group={{ user }}
    state=link
  with_items:
  - src:  i3blocks/conf
    dest: .config/i3blocks
  - src:  i3status.conf
    dest: .i3status.conf
  tags:
  - wm
  - gui
  - i3
