---
- name: ensure i3wm repository present
  apt_repository: >
    repo='deb http://debian.sur5r.net/i3/ trusty universe'
    state=present
    update_cache=yes
  tags:
  - wm
  - gui
  - i3

# FIXME; fix to use allow-unauthenticated somehow
- name: ensure i3wm keyring installed
  apt: >
    name=sur5r-keyring
    state=present
    # update_cache=yes
    # cache_valid_time=3600
    force=yes
  register: i3wm_keyring
  tags:
  - wm
  - gui
  - i3

- name: ensure apt cache is up do date if i3wm keyring was modified
  command: apt-get update
  when: i3wm_keyring.changed
  tags:
  - wm
  - gui
  - i3

- name: ensure i3wm packages installed
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
  - i3
  - i3-wm
  - i3lock
  - i3status
  - lxappearance
  - gtk-chtheme
  - qt4-qtconfig
  tags:
  - wm
  - gui
  - i3

- name: ensure i3wm config dir present
  file: >
    path=/home/{{ user }}/.i3
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=directory
  tags:
  - wm
  - gui
  - i3

- name: ensure i3wm config files present
  copy: >
    src=i3/i3config
    dest=/home/{{ user }}/.i3/config
    owner={{ user }}
    group={{ user }}
    mode=0644
  tags:
  - wm
  - gui
  - i3

- name: ensure i3status config present
  copy: >
    src=i3/i3status.conf
    dest=/home/{{ user }}/.i3status.conf
    owner={{ user }}
    group={{ user }}
    mode=0644
  tags:
  - wm
  - gui
  - i3
