---
- name: i3 | ensure configuration directory exists
  file:
    path:  "/home/{{ user }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode:  "0755"
    state: directory
  with_items:
  - .i3/
  - .i3/bin
  - .i3/i3blocks
  - .i3/i3blocks/bin
  - .i3/i3blocks/conf
  tags: ['wm', 'gui', 'i3']

- name: i3 | render configuration files
  template:
    dest: "/home/{{ user }}/.i3/{{ item }}"
    src:  "i3/{{ item }}.j2"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode:  "0644"
  with_items:
  - config
  - i3blocks/conf/config
  tags: ['wm', 'gui', 'i3']

- name: i3 | render supporting scripts
  template:
    dest:  "/home/{{ user }}/.i3/bin/{{ item }}"
    src:   "i3/bin/{{ item }}.j2"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode:  "0755"
  with_items:
  - startup
  - dmenu_marks
  - focus_mark
  - locker
  - mark
  - move_to_workspace
  - rename_workspace
  - workspace
  tags: ['wm', 'gui', 'i3']

- name: i3 | render i3blocks scripts
  template:
    dest: "/home/{{ user }}/.i3/i3blocks/bin/{{ item }}"
    src:  "i3/i3blocks/bin/{{ item }}.j2"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  with_items:
  - battery
  - disk
  - iface
  - mpc
  - newmail
  - scratchpad
  - volume
  - wifi
  tags: ['wm', 'gui', 'i3']

# FIXME; fix to use allow-unauthenticated somehow
- name: i3 | ensure i3wm keyring is installed
  apt:
    name: sur5r-keyring
    state: present
    force: yes
  register: i3wm_keyring
  tags: ['wm', 'gui', 'i3']

- name: i3 | ensure apt cache is up-do-date if i3wm keyring was modified
  command: apt-get update
  when: i3wm_keyring.changed
  tags: ['wm', 'gui', 'i3']

- name: i3 | ensure i3wm packages are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - i3
  - i3-wm
  - i3lock
  - i3status
  - lxappearance
  - gtk-chtheme
  - qt4-qtconfig
  - compton
  - suckless-tools
  tags: ['wm', 'gui', 'i3']

- name: i3 | ensure dunst configuration directory exists
  file:
    path:  /home/{{ user }}/.config/dunst
    owner: "{{ user }}"
    group: "{{ user }}"
    mode:  '0755'
    state: directory
  tags: ['wm', 'gui', 'i3']

- name: i3 | ensure dunst configuration is up to date
  template:
    dest:  /home/{{ user }}/.config/dunst/dunstrc
    src:   dunst/dunstrc.j2
    owner: "{{ user }}"
    group: "{{ user }}"
    mode:  '0644'
  tags: ['wm', 'gui', 'i3']

- name: i3 | include vars file
  include_vars: i3wm.yml
  tags: ['wm', 'gui', 'i3']

- name: i3 | check dropbox status
  command: dropbox.py status
  become: yes
  become_user: "{{ user }}"
  register: dropbox_status
  always_run: True
  changed_when: False
  tags: ['wm', 'gui', 'i3']

- name: i3 | print dropbox status if not up-to-date
  debug: var=dropbox_status.stdout
  when: dropbox_status.stdout not in ['Aktualny', 'Up to date']
  tags: ['wm', 'gui', 'i3']

- name: i3 | wait for dropbox if needed
  pause: prompt='Ensure Dropbox is ready before proceeding.'
  when: dropbox_status.stdout not in ['Aktualny', 'Up to date']
  tags: ['wm', 'gui', 'i3']

# apt module fails with weird errors when using 'with_items' with deb files
# https://github.com/ansible/ansible/issues/8314
# also, use force - those packages are likely to be held manually
- name: i3 | ensure self-compiled i3 is installed
  apt:
    deb: "/home/{{ user }}/Dropbox/ansible/packages/{{ i3gaps_debfile }}"
    state: present
    force: yes
  tags: ['wm', 'gui', 'i3']

- name: i3 | ensure self-compiled i3blocks is installed
  apt:
    deb: "/home/{{ user }}/Dropbox/ansible/packages/{{ i3blocks_debfile }}"
    state: present
    force: yes
  tags: ['wm', 'gui', 'i3']

- name: i3 | ensure i3status and i3blocks symlinks exist
  file:
    src: /home/{{ user }}/.i3/{{ item.src }}
    dest: /home/{{ user }}/{{ item.dest }}
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  with_items:
  - src:  i3blocks/conf
    dest: .config/i3blocks
  tags: ['wm', 'gui', 'i3']
