---
- name: check for compatible OS
  fail: >
    msg='Not running Ubuntu Trusty or x86_64'
  when: ansible_distribution_release != "trusty" or ansible_machine != 'x86_64'
  tags:
  - dependency

- include: general.yml
- include: user.yml
- include: git.yml
- include: zsh.yml
- include: hr.yml
- include: dotfiles.yml
- include: ruby.yml
# - include: powerline-shell.yml
# - include: powerline.yml
- include: gnome-terminal.yml
- include: gtk-themes.yml
- include: pi-rho-ppa.yml
- include: vim.yml
- include: tmux.yml
- include: ansible.yml
- include: cheat.yml
- include: doctools.yml
- include: utils.yml
- include: fzf.yml
- include: xmonad.yml
- include: i3wm.yml
- include: awesome.yml
- include: notifyosdconfig.yml
- include: ntp.yml
- include: comm.yml
- include: news.yml
- include: rainbowstream.yml
- include: media.yml
- include: networking.yml
- include: lxc.yml
- include: docker.yml
- include: vagrant.yml
- include: ranger.yml
- include: taskwarrior.yml
- include: go-tools.yml
- include: rbenv.yml
- include: mopidy.yml
# - include: haskell.yml
# - include: postgresql.yml
# - include: texlive.yml
