---
- name: ensure media packages installed
  apt: >
    name={{ item }}
    state=present
    update_cache=true
  with_items:
    - moc
    - autofs
    - mplayer
    - vlc
    - comix
    - museeq
    - qnapi
    - gimp
    - python3-pip
  tags:
  - media
  - gui

- name: ensure autofs configuration present
  copy: >
    src=autofs/auto.{{ item }}
    dest=/etc/auto.{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - master
    - nfs
  notify:
  - restart autofs
  tags:
  - media

- name: ensure autofs service running
  service: >
    name=autofs
    state=started
  tags:
  - media

# handled by dotfiles now
# - name: ensure moc config dir present
#   file: >
#     path=/home/{{ user }}/.moc
#     owner={{ user }}
#     group={{ user }}
#     mode=0750
#     state=directory

# - name: ensure moc themes dirs present
#   file: >
#     path=/home/{{ user }}/.moc/themes
#     owner={{ user }}
#     group={{ user }}
#     mode=0750
#     state=directory

# - name: ensure moc config files present
#   copy: >
#     src=moc/{{ item }}
#     dest=/home/{{ user }}/.moc/{{ item }}
#     owner={{ user }}
#     group={{ user }}
#     mode=0640
#   with_items:
#     - config
#     - keymap

# - name: ensure moc theme present
#   copy: >
#     src=moc/theme/simple-colored
#     dest=/home/{{ user }}/.moc/themes/simple-colored
#     owner={{ user }}
#     group={{ user }}
#     mode=0640

# TODO; fix keys - it's unauthenticated now as it is
# - name: ensure Spotify repo key present
#   apt_key: >
#     keyserver=keyserver.ubuntu.com
#     id=94558F59
#     state=present

# - name: ensure Spotify repository present
#   apt_repository: >
#     repo='deb http://repository.spotify.com stable non-free'
#     state=present
#     update_cache=yes

# - name: ensure Spotify installed
#   apt: >
#     name=spotify-client
#     state=present
- name: ensure subliminal installed
  pip: >
    name=subliminal
    state=present
  tags:
  - media
  - gui

- name: ensure mps-youtube installed
  pip: >
    name=mps-youtube
    state=present
    executable=pip3
  tags:
  - media
  - gui
