---
- name: ensure networking packages installed
  apt: >
    name={{ item }}
    state=present
    update_cache=true
    cache_valid_time=3600
  with_items:
    - ethtool
    - tcpdump
    - snmp
    - iftop
    - iotop
    - nmap
    - ftp
    - arp-scan
    - ipmitool
  tags:
  - networking
  - shelltools

- name: ensure wireshark configured
  debconf: >
    name=wireshark-common
    question='wireshark-common/install-setuid'
    vtype=boolean
    value=true
  tags:
  - networking
  - gui

- name: ensure wireshark installed
  apt: >
    name=wireshark
    state=present
    update_cache=true
    cache_valid_time=3600
  tags:
  - networking
  - gui
