---
- name: notify-osd | ensure apt keys for patched libnotify and notifyosdconfig are configured
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id={{ item }}
    state=present
  with_items:
  - 'E21DD54D' 
  - '4C9D234C'
  tags: ['gui', 'i3', 'awesome', 'xmonad']

- name: notify-osd | ensure repos for patched libnotify and notifyosdconfig are configured
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
  - 'ppa:leolik/leolik'
  - 'ppa:nilarimogard/webupd8'
  tags: ['gui', 'i3', 'awesome', 'xmonad']

- name: notify-osd | ensure patched notify-osd is installed from ppa
  apt: >
    name=notify-osd
    default_release='o=LP-PPA-leolik-leolik'
    state=present
    update_cache=yes
    cache_valid_time=3600
  tags: ['gui', 'i3', 'awesome', 'xmonad']

- name: notify-osd | ensure notifyosdconfig is installed
  apt: >
    name=notifyosdconfig
    state=present
    update_cache=yes
    cache_valid_time=3600
  notify:
  - restart notify-osd
  tags: ['gui', 'i3', 'awesome', 'xmonad']
