---
- name: ensure ntp configuration file is available
  template: >
    src=ntp/ntp.conf.j2
    dest=/etc/ntp.conf
    owner=root
    group=root
    mode=0644
  notify:
  - restart ntp
  tags:
  - ntp

- name: ensure ntp service is running
  service: >
    name=ntp
    state=started
  tags:
  - ntp
