---
- name: ensure powerline dir present
  file: >
    path=/home/{{ user }}/.powerline
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=directory

- name: ensure powerline-shell repo cloned
  git: >
    repo='https://github.com/moon-musick/powerline-shell'
    dest=/home/{{ user }}/.powerline/powerline-shell
    update=no
  # sudo_user: "{{ user }}"

# FIXME
- name: ensure proper permissions set
  command: chown -R {{ user }}:{{ user }} /home/{{ user }}/.powerline/

- name: ensure installation config present
  copy: >
    src=powerline/config.py
    dest=/home/{{ user }}/.powerline/powerline-shell/config.py
    owner={{ user }}
    group={{ user }}
    mode=0640

# FIXME; permissions bug
# - name: ensure installation script run
#   command: './install.py'
#   args:
#     chdir: "/home/{{ user }}/.powerline/powerline-shell"
#     creates: "/home/{{ user }}/.powerline/powerline-shell/powerline-shell.py"
#   sudo_user: "{{ user }}"
