---
# activation stuff already added to shell rc files
- name: ensure rbenv cloned
  git: >
    repo='https://github.com/sstephenson/rbenv.git'
    dest=/home/{{ user }}/.rbenv
  sudo_user: "{{ user }}"
  tags:
  - dev
  - ruby

# most likely unnecessary
- name: ensure rbenv plugins dir present
  file: >
    path=/home/{{ user }}/.rbenv/plugins
    owner={{ user }}
    group={{ user }}
    mode=0775
    state=directory
  tags:
  - dev
  - ruby

- name: ensure rbenv plugins installed
  git: >
    repo={{ item.repo }}
    dest=/home/{{ user }}/.rbenv/plugins/{{ item.name }}
  sudo_user: "{{ user }}"
  with_items:
    - name: rbenv-gem-rehash
      repo: https://github.com/sstephenson/rbenv-gem-rehash.git
    - name: rbenv-gemset
      repo: https://github.com/jf/rbenv-gemset.git
    - name: rbenv-sudo
      repo: https://github.com/dcarley/rbenv-sudo.git
    - name: rbenv-update
      repo: https://github.com/rkh/rbenv-update.git
    - name: rbenv-use
      repo: https://github.com/rkh/rbenv-use.git
    - name: rbenv-whatis
      repo: https://github.com/rkh/rbenv-whatis.git
    - name: ruby-build
      repo: https://github.com/sstephenson/ruby-build.git
  tags:
  - dev
  - ruby

# TODO; install basic ruby?
