---
- name: rofi | include vars file
  include_vars: rofi.yml
  tags: ['gui', 'i3', 'awesome', 'xmonad', 'rofi'] 

- name: rofi | ensure rofi is installed
  apt:
    deb: "/home/{{ user }}/Dropbox/ansible/packages/{{ rofi_debfile }}"
    state: present
  tags: ['gui', 'i3', 'awesome', 'xmonad', 'rofi'] 
