---
- name: ensure dependencies installed
  apt: >
    name={{ item }}
    state=installed
  with_items:
    - perl-modules
    - wget

- name: ensure installation script present
  get_url: >
    url=http://mirror.unl.edu/ctan/systems/texlive/tlnet/install-tl-unx.tar.gz
    dest=/tmp/install-tl-unx.tar.gz
  changed_when: False

- name: unarchive installation script
  command: tar xfz /tmp/install-tl-unx.tar.gz
  args:
    chdir: /tmp/
  changed_when: False

- name: ensure installation profile present
  template: >
    src=texlive/texlive.profile.j2
    dest=/tmp/texlive.profile
    owner=root
    group=root
    mode=0644
  changed_when: False

- name: ensure texlive installed
  shell: cd /tmp/install-tl-* && ./install-tl -profile /tmp/texlive.profile
  args:
    creates: /usr/local/texlive/{{ texlive_version }}/bin/x86_64-linux/xelatex
