---
- name: tmux | ensure tmux is installed
  apt: >
    name=tmux
    state=present
  tags: ['shelltools', 'tmux']

- name: tmux | ensure tmux configuration directory is present
  file: >
    path=/home/{{ user }}/{{ item }}
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=directory
  with_items:
  - '.tmux'
  - '.tmux/plugins'
  tags: ['shelltools', 'tmux']

- name: tmux | ensure tpm repo was cloned
  git: >
    repo='https://github.com/tmux-plugins/tpm'
    dest=/home/{{ user }}/.tmux/plugins/tpm
  become_user: "{{ user }}"
  tags: ['shelltools', 'tmux']
