---
- name: ensure main user exists
  user: >
    name={{ user }}
    generate_ssh_key=yes
    groups=sudo,adm,lpadmin,dip,cdrom,plugdev,sambashare
    home=/home/{{ user }}
    createhome=yes
    shell=/usr/bin/zsh
