---
- name: ensure necessary groups exist
  group: >
    name={{ item }}
    state=present
    system=yes
  with_items:
  - lxd
  - libvirtd
  - docker
  tags:
  - user
  - dependency

- name: ensure main user exists
  user: >
    name={{ user }}
    generate_ssh_key=no
    groups=sudo,adm,lpadmin,dip,cdrom,plugdev,sambashare,libvirtd,lxd,docker
    home=/home/{{ user }}
    createhome=yes
    shell=/usr/bin/zsh
  tags:
  - user
  - dependency

- name: ensure necessary directories exist
  file: >
    path=/home/{{ user }}/{{ item }}
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=directory
  with_items:
  - ansible
  - dev
  - bin
  tags:
  - user
  - dependency
