---
# TODO; replace with shell function where possible
- name: utilities | ensure utility scripts are present
  copy: >
    src=scripts/{{ item }}
    dest=/home/{{ user }}/bin/{{ item }}
    owner={{ user }}
    group={{ user }}
    mode=0755
  with_items:
  - freeze
  - lock
  - locker
  - nemo
  - trash
  - wlan_reconnect
  - fx
  tags: ['gui', 'shelltools']

- name: utilities | ensure lock on sleep script added
  copy: >
    src=scripts/10_lock
    dest=/etc/pm/sleep.d/10_lock
    owner=root
    group=root
    mode=0755
  tags: ['gui']
