---
- name: ensure vagrant deb file is locally available
  get_url: >
    url='https://dl.bintray.com/mitchellh/vagrant/{{ vagrant_debfile }}'
    dest=/home/{{ user }}/ansible/{{ vagrant_debfile }}
    owner={{ user }}
    group={{ user }}
    mode=0644
  tags:
  - virttools
  - dev

- name: ensure vagrant is installed
  apt: >
    deb=/home/{{ user }}/ansible/{{ vagrant_debfile }}
    state=present
  tags:
  - virttools
  - dev
