---
- name: ensure packages installed
  apt: >
    name={{ item }}
    state=present
  with_items:
    - vim-nox
    - vim-gtk
    - git
    - cmake
    - ack-grep
    - silversearcher-ag
    - exuberant-ctags
    - build-essential
    - python-dev # ctrlp-cmatcher
    # - ghc-mod
    # - hdevtools

- name: ensure repo cloned
  git: >
    repo={{ vim_repo }}
    dest=/home/{{ user }}/.vim
    update=no
    accept_hostkey=yes
  sudo_user: "{{ user }}"

# FIXME; does not terminate properly
# - name: ensure plugins installed
#   command: vim -u /home/{{ user }}/.vim/custom/vundle.vim +PluginInstall +qall
#   args:
#     creates: /home/{{ user }}/.vim/bundle/YouCompleteMe
#   sudo_user: "{{ user }}"

# FIXME; permissions bug
# - name: ensure proper permissions set
#   command: chown -R {{ user }}:{{ user }} /home/{{ user }}/.vim

# - name: ensure other dependencies installed
#   TODO; gem install rcodetools # vim-xmpfilter

# FIXME; permissions bug
- name: ensure installation script run
  command: "/home/{{ user }}/.vim/install.sh"
  args:
    creates: "/home/{{ user }}/.vim/install.lock"
  sudo_user: "{{ user }}"

- name: ensure vimrc symlink created
  file: >
    src=/home/{{ user }}/.vim/.vimrc
    path=/home/{{ user }}/.vimrc
    owner={{ user }}
    group={{ user }}
    state=link
