---
- name: ensure xmonad repo cloned
  git: >
    repo='https://github.com/moon-musick/xmonad-ubuntu-conf'
    dest=/home/{{ user }}/.xmonad
    update=no
  sudo_user: "{{ user }}"

- name: ensure installation script run
  command: "/home/{{ user }}/.xmonad/install-xmonad"
  args:
    creates: "/home/{{ user }}/.xmonad/install.lock"
