---
# taskwarrior-related bug - tab completion crashes zsh
# backports version is fixed
- name: zsh | ensure zsh is installed
  apt: >
    name=zsh
    state=present
    default_release=trusty-backports
  tags: ['shelltools', 'dependency']

- name: zsh | ensure oh-my-zsh is installed
  git: >
    repo='https://github.com/robbyrussell/oh-my-zsh'
    dest=/home/{{ user }}/.oh-my-zsh
  become: yes
  become_user: "{{ user }}"
  tags: ['shelltools']

- name: zsh | ensure zsh custom dir is present
  file: >
    path=/home/{{ user }}/.zsh
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=directory
  tags: ['shelltools']

- name: zsh | ensure notification script is present
  copy: >
    src=zsh/notifyosd.zsh
    dest=/home/{{ user }}/.zsh/notifyosd.zsh
    owner={{ user }}
    group={{ user }}
    mode=0664
  tags: ['shelltools']

- name: zsh | ensure syntax highlighting plugin is present
  git: >
    repo='https://github.com/zsh-users/zsh-syntax-highlighting'
    dest=/home/{{ user }}/.zsh/zsh-syntax-highlighting
  become_user: "{{ user }}"
  tags: ['shelltools']

- name: zsh | ensure text-objects plugin is present
  git: >
    repo='https://github.com/hchbaw/opp.zsh'
    dest=/home/{{ user }}/.zsh/opp.zsh
  become_user: "{{ user }}"
  tags: ['shelltools']

- name: zsh | ensure additional completions are available
  git: >
    repo='https://github.com/zsh-users/zsh-completions'
    dest=/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-completions
  become_user: "{{ user }}"
  tags: ['shelltools']
