---
- name: doctools | ensure Mendeleydesktop PPA key is configured
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id=6F036044
    state=present
  tags: ['gui', 'doctools']

- name: doctools | ensure Mendeleydesktop PPA is configured
  apt_repository: >
    repo='deb http://desktop-download.mendeley.com/download/apt stable main'
    state=present
    update_cache=yes
  tags: ['gui', 'doctools']

- name: doctools | ensure Zeal PPA key is configured
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id=2FF96FD1
    state=present
  tags: ['gui', 'doctools']

- name: doctools | ensure Zeal PPA is configured
  apt_repository: >
    repo='ppa:zeal-developers/ppa'
    state=present
    update_cache=yes
  tags: ['gui', 'doctools']

- name: doctools | ensure doctools packages are installed
  apt: >
    name={{ item }}
    state=present
  with_items:
    - zeal
    - zathura
    - mendeleydesktop
  tags: ['gui', 'doctools']

# https://github.com/zealdocs/zeal/issues/134
- name: doctools | ensure appmenu-qt5 is not installed
  apt:
    name:  appmenu-qt5
    state: absent
  tags: ['gui', 'doctools']
