---
- name: dotfiles | ensure rcm debfile is available
  copy: >
    src={{ rcm_debfile }}
    dest=/home/{{ user }}/ansible/{{ rcm_debfile }}
    owner={{ user }}
    group={{ user }}
    mode=0644
  tags: ['shelltools']

- name: dotfiles | ensure rcm is installed
  apt: >
    deb=/home/{{ user }}/ansible/{{ rcm_debfile }}
    state=present
  tags: ['shelltools']

- name: dotfiles | ensure dotfiles repo was cloned
  git: >
    repo='git@github.com:moon-musick/.dotfiles.git'
    dest=/home/{{ user }}/.dotfiles
  become_user: "{{ user }}"
  tags: ['shelltools']

# .haskeline least likely to be present before
- name: dotfiles | ensure dotfiles symlinks are in place
  command: rcup -x README.md -f
  become_user: "{{ user }}"
  args:
    chdir: /home/{{ user }}
    creates: /home/{{ user }}/.haskeline
  tags: ['shelltools']
