---
- name: go | ensure directories present
  file: >
    path=/home/{{ user }}/go
    owner={{ user }}
    group={{ user }}
    mode=0755
    state=directory
  tags: ['dev', 'shelltools', 'golang']

- name: go | ensure go downloaded
  get_url: >
    url="https://storage.googleapis.com/golang/{{ golang_tarball }}"
    dest=/home/{{ user }}/ansible/{{ golang_tarball }}
  register: golang_archive_downloaded
  tags: ['dev', 'shelltools', 'golang']

# remnants of old installation cause errors
# http://stackoverflow.com/questions/32115229/go-1-5-error-imports-runtime-c-source-files-not-allowed-when-not-using-cgo-o
- name: go | remove old go if new version downloaded
  file:
    path:  /usr/local/go
    state: absent
  when: golang_archive_downloaded.changed
  tags: ['dev', 'shelltools', 'golang']

- name: go | unarchive golang tarball
  unarchive: >
    src=/home/{{ user }}/ansible/{{ golang_tarball }}
    dest=/usr/local
    copy=no
  when: golang_archive_downloaded.changed
  tags: ['dev', 'shelltools', 'golang']

- name: go | add apt prerequisites
  apt:
    name:  "{{ item }}"
    state: present
  with_items:
  - libxrandr-dev
  tags: ['dev', 'shelltools', 'golang']

- name: go | ensure go apps installed
  shell: GOPATH=/home/{{ user }}/go /usr/local/go/bin/go get {{ item.repo }}
  args:
    creates: /home/{{ user }}/go/bin/{{ item.exec }}
  with_items:
    - exec: orange
      repo: github.com/noraesae/orange-cat/cmd/orange
    - exec: wego
      repo: github.com/schachmat/wego
    - exec: asciinema
      repo: github.com/asciinema/asciinema
    - exec: sift
      repo: github.com/svent/sift
    - exec: hostess
      repo: github.com/cbednarski/hostess/cmd/hostess
    - exec: peco
      repo: github.com/peco/peco/cmd/peco
    - exec: sct
      repo: github.com/d4l3k/go-sct/sct
    - exec: weather
      repo: github.com/jfrazelle/weather
  become_user: "{{ user }}"
  tags: ['dev', 'shelltools', 'golang']

- name: go | include wego vars file
  include_vars: wego.yml
  tags: ['shelltools', 'golang']

- name: go | ensure wego configuration file is present
  template: >
    src=wego/wegorc.j2
    dest=/home/{{ user }}/.wegorc
    owner={{ user }}
    group={{ user }}
    mode=0600
  tags: ['shelltools', 'golang']
