---
- name: lxc | ensure LXD stable PPA key is configured
  apt_key: >
    id=7635B973
    keyserver=keyserver.ubuntu.com
    state=present
  tags: ['virttools', 'dev']

- name: lxc | ensure LXD stable PPA is configured
  apt_repository: >
    repo='ppa:ubuntu-lxc/lxd-stable'
    state=present
    update_cache=yes
  tags: ['virttools', 'dev']

- name: lxc | ensure LXC and LXD packages are installed
  apt: >
    name={{ item }}
    state=present
  with_items:
    - lxc
    - lxd
    - lxd-client
  tags: ['virttools', 'dev']
