---
- name: media | ensure media packages are installed
  apt: >
    name={{ item }}
    state=present
    update_cache=true
    cache_valid_time=3600
  with_items:
    - moc
    - autofs
    - mplayer
    - vlc
    - comix
    - gimp
    - python3-pip
  tags: ['media', 'gui']

- name: media | ensure autofs configuration is present
  copy: >
    src=autofs/auto.{{ item }}
    dest=/etc/auto.{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - master
    - nfs
  notify:
  - restart autofs
  tags: ['media']

- name: media | ensure autofs service is running
  service: >
    name=autofs
    state=started
  tags: ['media']

# TODO; fix keys - it's unauthenticated now as it is
# - name: media | ensure Spotify repo key is configured
#   apt_key: >
#     keyserver=keyserver.ubuntu.com
#     id=94558F59
#     state=present
#   tags: ['media', 'gui']

# - name: media | ensure Spotify repository is configured
#   apt_repository: >
#     repo='deb http://repository.spotify.com stable non-free'
#     state=present
#     update_cache=yes
#   tags: ['media', 'gui']

# - name: media | ensure Spotify is installed
#   apt: >
#     name=spotify-client
#     state=present
#   tags: ['media', 'gui']

- name: media | ensure subliminal is installed
  pip: >
    name=subliminal
    state=present
  tags: ['media', 'gui']

- name: media | ensure mps-youtube is installed
  pip: >
    name=mps-youtube
    state=present
    executable=pip3
  tags: ['media', 'gui']
