---
- name: mopidy | include vars files
  include_vars: '{{ item }}'
  with_items:
  - lastfm.yml
  - spotify.yml
  tags: ['media', 'music']

- name: mopidy | ensure mopidy repo key is present
  apt_key: >
    url='https://apt.mopidy.com/mopidy.gpg'
    state=present
  tags: ['media', 'music']

- name: mopidy | ensure mopidy repo is configured
  apt_repository:
    repo:         "{{ item }}"
    state:        present
    update_cache: yes
  with_items:
  - 'deb http://apt.mopidy.com/ jessie main contrib non-free'
  - 'deb-src http://apt.mopidy.com/ jessie main contrib non-free'
  tags: ['media', 'music']

- name: mopidy | ensure mopidy is installed
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
  - mopidy
  - mopidy-spotify
  - mopidy-scrobbler
  - mopidy-alsamixer
  - ncmpcpp
  - mpc
  tags: ['media', 'music']

- name: mopidy | ensure mopidy directories are present
  file: >
    path=/home/{{ user }}/{{ item.path }}
    owner={{ user }}
    group={{ user }}
    mode={{ item.mode }}
    state=directory
  with_items:
  - { path: '.config/mopidy',    mode: '0700' }
  - { path: '.mopidy',           mode: '0700' }
  - { path: '.mopidy/log',       mode: '0700' }
  - { path: '.mopidy/cache',     mode: '0700' }
  - { path: '.mopidy/data',      mode: '0700' }
  - { path: '.mopidy/playlists', mode: '0700' }
  tags: ['media', 'music']

- name: mopidy | ensure templated configuration is up to date
  template: >
    src=mopidy/{{ item.name }}.j2
    dest={{ item.basepath }}/{{ item.name }}
    owner={{ item.owner }}
    group={{ item.owner }}
    mode={{ item.mode }}
  with_items:
  - name: 'mopidy.conf'
    basepath: '/home/{{ user }}/.config/mopidy'
    mode: '0600'
    owner: '{{ user }}'
  - name: 'logging.conf'
    basepath: '/home/{{ user }}/.config/mopidy'
    mode: '0600'
    owner: '{{ user }}'
  notify:
  - restart mopidy
  tags: ['media', 'music']

# run as user with window manager start
- name: mopidy | ensure system service is disabled
  service: >
    name=mopidy
    enabled=no
  tags: ['media', 'music']

- name: mopidy | ensure system service is not running
  service: >
    name=mopidy
    state=stopped
  tags: ['media', 'music']
