---
- name: networking | ensure networking packages are installed
  apt: >
    name={{ item }}
    state=present
    update_cache=true
    cache_valid_time=3600
  with_items:
    - ethtool
    - tcpdump
    - snmp
    - iftop
    - iotop
    - nmap
    - ftp
    - arp-scan
    - ipmitool
  tags: ['networking', 'shelltools']

- name: networking | ensure wireshark is pre-configured
  debconf: >
    name=wireshark-common
    question='wireshark-common/install-setuid'
    vtype=boolean
    value=true
  tags: ['networking', 'shelltools']

- name: networking | ensure wireshark is installed
  apt: >
    name=wireshark
    state=present
    update_cache=true
    cache_valid_time=3600
  tags: ['networking', 'shelltools']
