---
- name: ph-rho | ensure tmux PPA key is configured
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id=779C27D7
    state=present
  tags: ['shelltools', 'vim', 'tmux']

- name: ph-rho | ensure tmux PPA is configured
  apt_repository: >
    repo='ppa:pi-rho/dev'
    state=present
    update_cache=yes
  tags: ['shelltools', 'vim', 'tmux']
