---
- name: ruby | ensure brightbox PPA key is configured
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id='C3173AA6'
    state=present
  tags: ['ruby', 'dev', 'dependency']

- name: ruby | ensure brightbox PPA is configured
  apt_repository: >
    repo='ppa:brightbox/ruby-ng'
    state=present
    update_cache=yes
  tags: ['ruby', 'dev', 'dependency']

- name: ruby | ensure brightbox ruby is installed
  apt: >
    name={{ item }}
    state=present
  with_items:
  - ruby2.2
  - ruby2.2-dev
  tags: ['ruby', 'dev', 'dependency']

- name: ruby | ensure bundler is installed
  gem: >
    name=bundler
    state=present
    user_install=no
  tags: ['ruby', 'dev', 'shelltools']

- name: ruby | ensure ruby-dependent tools are installed
  gem: >
    name={{ item }}
    state=present
    user_install=no
  with_items:
  - fpm
  - tmuxinator
  tags: ['ruby', 'dev', 'shelltools']
