---
- name: vim | ensure vim packages are installed
  apt: >
    name={{ item }}
    state=present
  with_items:
    - vim-nox
    - vim-gtk
    - git
    - cmake
    - ack-grep
    - silversearcher-ag
    - exuberant-ctags
    - build-essential
    - python-dev # ctrlp-cmatcher
    # - ghc-mod
    # - hdevtools
  tags: ['shelltools', 'dev', 'vim']

# apparently the module returns 'changed' on every checkout
# even if remote was not updated in any way
- name: vim | ensure vim repo was cloned
  git: >
    repo={{ vim_repo }}
    dest=/home/{{ user }}/.vim
    accept_hostkey=yes
    track_submodules=no
  changed_when: False
  become_user: "{{ user }}"
  tags: ['shelltools', 'dev', 'vim']

# FIXME; test termination issues
- name: vim | ensure plugins are installed
  shell: vim -u custom/vundle.vim +PluginInstall +qall
  args:
    creates: /home/{{ user }}/.vim/bundle/YouCompleteMe
    chdir: /home/{{ user }}/.vim
  become_user: "{{ user }}"
  tags: ['shelltools', 'dev', 'vim']

- name: vim | ensure vim setup script was run
  command: "/home/{{ user }}/.vim/install.sh"
  args:
    creates: "/home/{{ user }}/.vim/install.lock"
  become_user: "{{ user }}"
  tags: ['shelltools', 'dev', 'vim']

- name: vim | ensure vimrc symlink is in place
  file: >
    src=/home/{{ user }}/.vim/.vimrc
    path=/home/{{ user }}/.vimrc
    owner={{ user }}
    group={{ user }}
    state=link
  tags: ['shelltools', 'dev', 'vim']
