---
- name: apt-get update
  command: apt-get update

- name: restart autofs
  service: >
    name=autofs
    state=restarted

- name: restart ssh
  service: >
    name=ssh
    state=restarted

- name: restart ntp
  service: >
    name=ntp
    state=restarted

- name: restart supervisord
  service: >
    name=supervisord
    state=restarted
