---
- name: apt-get update
  command: apt-get update

- name: restart autofs
  service: >
    name=autofs
    state=restarted

- name: restart ssh
  service: >
    name=ssh
    state=restarted

- name: restart ntp
  service: >
    name=ntp
    state=restarted

- name: restart mopidy
  service: >
    name=mopidy
    state=restarted

- name: restart notify-osd
  command: pkill notify-osd
