---
- name: git | ensure git PPA key is configured
  apt_key:
    keyserver: keyserver.ubuntu.com
    id:        E1DF1F24
    state:     present
  tags: ['dev', 'shelltools', 'dependency']

- name: git | ensure git PPA is configured
  apt_repository:
    repo:         'ppa:git-core/ppa'
    state:        present
    update_cache: yes
  tags: ['dev', 'shelltools', 'dependency']

- name: git | ensure git is installed
  apt:
    name:  git
    state: present
  tags: ['dev', 'shelltools', 'dependency']

- name: git | ensure additional tools are installed
  pip:
    name:  joe
    state: present
  tags: ['dev', 'shelltools']

- name: git | ensure additional packages are installed
  apt:
    name:  "{{ item }}"
    state: present
  with_items:
  - tig
  tags: ['dev', 'shelltools']
